app/models.py
from . import db
from . import login_manager
from flask_login import  UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True, index = True)
    password = db.Column(db.String(255))
    pass_secure = db.Column(db.String(255))
    password_hash = db.Column(db.String(255))

    #Definig user to pitch relationship
    pitch = db.relationship('Pitch',backref = 'user',lazy = 'dynamic')

    #Create user to comment relationship
    comment = db.relationship('Comment', backref='main_user', lazy='dynamic')

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    # def set_password(self, password):
    #     self.pass_secure = generate_password_hash(password)

    @password.setter
    def password(self,password):
        self.pass_secure = generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    def __repr__(self):
        return f'User{self.username}'

class Category(db.Model):
    __tablename__ = 'categories'

    id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.String(255))
    pitch = db.relationship('Pitch', backref='parent_category', lazy='dynamic')

    def __repr__(self):
        return f'Category {self.name}'

class Pitch(db.Model):
    __tablename__ = 'pitches'

    id =  db.Column(db.Integer, primary_key = True)
    title = db.Column(db.String(255))
    pitch_body = db.Column(db.String)
    body = db.Column(db.String)
    #Defining user relationship
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))
    #Define category relationship
    category_id = db.Column(db.Integer, db.ForeignKey("categories.id"))
    #Defining one relationship with comments
    comments = db.relationship('Comment', backref="main_pitch", cascade="all, delete-orphan", lazy="dynamic")
    def __repr__(self):
        return f'Pitch {self.title}'

class Comment(db.Model):
    __tablename__ = 'comments'

    id =  db.Column(db.Integer, primary_key = True)
    author = db.Column(db.String(255))
    comment = db.Column(db.String)
    # Defining the foreign key from the relationship between a pitch and a comment
    pitch_id = db.Column(db.Integer, db.ForeignKey("pitches.id"))

    # Defining the foreign key from the relationship between a user and a comment
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))

    def __repr__(self):
        return f'Comment {self.comment}'

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField,SubmitField
from ..models import Pitch, Comment
from wtforms.validators import DataRequired

class PitchForm(FlaskForm):
    title = StringField('Pitch Category Title', validators=[DataRequired()])
    body = TextAreaField('Enter your Pitch here', validators=[DataRequired()])
    submit = SubmitField('Submit')

class CommentForm(FlaskForm):
    comment = TextAreaField('Write a comment here',validators=[DataRequired()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options,Config
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet, configure_uploads, IMAGES
from flask_mail import Mail
from flask_simplemde import SimpleMDE

simple = SimpleMDE()
db = SQLAlchemy()
bootstrap = Bootstrap()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
photos = UploadSet('photos', IMAGES)
mail = Mail()


def create_app(config_name):
    app = Flask(__name__)

    # Creating the app configurations

    app.config.from_object(config_options[config_name])
    config_options[config_name].init_app(app)

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    simple.init_app(app)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # # setting config
    # from .request import configure_request
    # configure_request(app)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/authenticate')

    # configuring uploadset
    # configure_uploads(app, photos)

    # Initialixing the mail app
    mail.init_app(app)

    return app

app/main/__init__.py
from flask import Blueprint
main= Blueprint('main',__name__)
from .import views,errors

app/main/views.py
from flask import render_template,url_for,flash,redirect,request,abort
from . import main
from .forms import PitchForm, CommentForm
from ..models import User, Pitch, Category, Comment
from ..import db
from flask_login import login_required,current_user

@main.route('/')
def index():
    """View root function that returns index"""
    title =  'Home | welcome to pitches'
    return render_template('index.html', title = title)

@main.route('/pitch/new',methods=["GET","POST"])
def new_pitch():
    form = PitchForm()
    if form.validate_on_submit():
        pitch = Pitch(title = form.title.data, body = form.body.data)
        db.session.add(pitch)
        db.session.commit()
        flash('Nice pitching!')
        return redirect (url_for('main.new_pitch'))
    title = "Show us what you've got"
    pitches = Pitch.query.all()

    return render_template('pitch.html', title=title, form=form, pitch_list=pitches)

@main.route('/comment/new', methods = ["GET", "POST"])
@login_required
def new_comment():
    comment_form = CommentForm()
    if comment_form.validate_on_submit():
        comment = Comment(comment=comment_form.comment.data)
        db.session.add(comment)
        db.session.commit()
        flash('Your comment has been posted succesfully')
        return redirect(url_for('main.new_comment'))
    comments = Comment.query.all()
    return render_template('form.html', comment_form=comment_form, comment_list=comments)


@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username=uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user=user)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)
    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))
    return render_template('profile/update.html',form=form)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

app/templates/base.html
{% extends 'bootstrap/base.html'%}

<!-- Navbar block  -->
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}
{%block styles %}
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.1.3/cyborg/bootstrap.min.css" rel="stylesheet" integrity="sha384-4DAPMwiyOJv/C/LvTiUsW5ueiD7EsaAhwUKO0Llp+fWzT40XrmAbayhVP00bAJVa" crossorigin="anonymous">

  {{super()}}
  <!--Importing the simple mde css and js files  -->
  {{ simplemde.css}}
  {{ simplemde.js }}

{% endblock %}

app/templates/form.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}
{% import 'macros.html' as macro %}

{% block navbar%}
    {%include 'navbar.html'%}
{% endblock %}

{%block styles%}{{super()}}{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        {{wtf.quick_form(comment_form)}}
    </div>
    <div class="col-md-3"></div>
</div>
<div class="col-md-3"></div>
    <div class="col-md-6">
      {{macro.displayCommentList(comment_list)}}
    </div>
    <div class="col-md-3"></div>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{%block content%}
<div class="container">
  <div class="row">
    <h1>Shoot your shot!</h1>
  </div>
  <div class="row">
    <div class="col-md-5">
      <div class="card homecard" style="width: 48rem; height:30rem;">
        <img class="card-img-top" src="{{url_for('static', filename='product.jpeg')}}" alt="Card image cap">
        <div class="card-body">
          <p class="card-text" style="color:white">Product pitch</p>
        </div>
      </div>
    </div>
    <div class="col-md-1"> </div>
    <div class="col-md-5">
      <div class="card homecard" style="width: 48rem; height:30rem;">
        <img class="card-img-top" src="{{url_for('static', filename='heart.jpeg')}}" alt="Card image cap">
        <div class="card-body">
          <p class="card-text" style="color:white">Pick up lines</p>
        </div>
      </div>
    </div>

  </div>
</div>
{% endblock %}

app/templates/macros.html
{% macro displayPitchList(pitch_list) %}
{% for pitch in pitch_list %}
<div class="col-md-1">
</div>
<div class="col-md-10">
  <div class="card m-6">
    <div class="card-header">
      <h3 class="card-title">{{pitch.title}}</h3>
    </div>
    <div class="card-body">
      <p class="card-text">{{pitch.body}}</p>
    </div>
    <hr>
    <div class="card-footer">
      <a href="{{ url_for('main.new_comment') }}">Comment</a>
    </div>
  </div>
</div>
<div class="col-md-1">
</div>
{% endfor %}
{% endmacro %}
{% macro displayCommentList(comment_list) %}
{% for review in comment_list %}
<div class="col-md-3">
</div>
<div class="col-md-6">
  <p>{{review.comment}}</p>
</div>
<div class="col-md-3">
</div>

{% endfor %}
{% endmacro %}

app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">Pitch</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="/">Home <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link active" href="{{ url_for('main.new_pitch') }}">New Pitch</a>
      <a class="nav-item nav-link active" href="{{url_for('main.profile',uname=current_user.username)}}">My Profile</a>
       <ul class="nav navbar-nav navbar-right d-flex flex-row bd-highlight mb-3">
        {% if current_user.is_authenticated %}

        <li class="p-2 bd-highlight"><a class="nav-item nav-link" href="{{ url_for('main.new_pitch') }}">Submit A Pitch</a></li>

        <li><a href="{{url_for('main.index',uname=current_user.username)}}">Profile</a></li>
        <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
        {% else %}
        <li class="p-2 bd-highlight"><a href="{{url_for('auth.register')}}">Register</a></li>
        <li class="divider"></li>
        <li class="p-2 bd-highlight"><a href="{{url_for('auth.login')}}">Sign In</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

app/templates/pitch.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf%}
{% import 'macros.html' as macro %}
{% block navbar %}
  {% include 'navbar.html'%}
{% endblock %}
{% block content %}

<div class="container-fluid">
  <h1 class="text-center">Shoot your shot!</h1>
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.body.label(class="form-control-label") }}
                {% if form.body.errors %}
                    {{ form.body(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.body(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>

</div>

</div>

<hr>
<!-- Content block -->
<div class="container-fluid mt-3">
  <div class="row">
      {{macro.displayPitchList(pitch_list)}}

  </div>
</div>
{% endblock content %}

app/templates/profile/profile.html
{% extends 'base.html'%}
{% block content %}
<div class="container">
    <div class="row">
        #display the user Username
        <div class="col-md-4">
            <h3>{{user.username| capitalize}}</h3>
            #display user bio
            {% if user.bio %}
            <p>{{user.bio}}</p>
            {% else %}
            <p>{{user.username| capitalize}} has no bio</p>
            {% endif %}
            {% if user == current_user %}
             <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
            {% endif %}
        </div>
        #display profile photo
        <div class="col-md-4">
            {% if user.profile_pic_path %}
            <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
            {% else %}
            <p>No profile picture</p>
            {% endif %}
            {% if user == current_user %}
            <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">
            <input type="file"  name="photo" class="form-control" required>
            <input type="submit">
            </form>
            {% endif %}
        </div>

        </div>
    </div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}